backend:
  name: git-gateway

media_folder: static/assets
public_folder: assets

collections:
  - label: "Settings"
    name: "settings"
    files:
      - label: "Navbar"
        name: "navbar"
        file: content/settings/navbar/navbar.json
        fields:
          - {label: 'CTA Text', name: ctaText, widget: string}
          - label: Links
            name: links
            widget: list
            fields:
              - label: label
                name: label
                width: string
              - label: to
                name: to
                width: string
      - label: "Footer"
        name: "footer"
        file: content/settings/footer/footer.json
        fields:
          - {label: Copyright, name: copyright, widget: string}
          - {label: 'Made In', name: madeIn, widget: string}
          - label: 'Link Groups'
            name: linkGroups
            widget: list
            fields:
              - label: Title
                name: title
                width: string
              - label: Links
                name: links
                widget: list
                fields:
                  - label: Label
                    name: label
                    width: string
                  - label: To
                    name: to
                    width: string
  - name: doc
    label: Doc
    folder: content/docs
    create: true
    fields:
      - {name: path, label: Path}
      - {name: title, label: Title}
      - label: Category
        name: category
        widget: select
        options: ["Getting Started", "Guides", "FAQ"]
      - {name: body, label: Body, widget: markdown}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Help"
        name: "help"
        file: content/pages/help/help.json
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: 'Contact Us Text', name: contactUsText, widget: string}
          - {label: 'Contact Us CTA', name: contactUsCta, widget: string}
          - {label: 'Contact Us Title', name: contactUsTitle, widget: string}
          - {label: 'Contact Us Email', name: contactUsEmail, widget: string}
          - {label: 'Blog Text', name: blogText, widget: string}
          - {label: 'Blog CTA', name: blogCta, widget: string}
          - {label: 'Blog Title', name: blogTitle, widget: string}
          - {label: 'Twitter Text', name: twitterText, widget: string}
          - {label: 'Twitter CTA', name: twitterCta, widget: string}
          - {label: 'Twitter Title', name: twitterTitle, widget: string}
          - label: 'Footer CTA'
            name: footerCta
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: subtitle
                name: subtitle
                widget: string
              - label: 'CTA Text'
                name: ctaText
                widget: string
      - label: "Pricing"
        name: "pricing"
        file: content/pages/pricing/pricing.json
        fields:
          - {label: Title, name: title, widget: string}
          - label: Standard
            name: standard
            widget: object
            fields:
              - label: Price Per Month
                name: pricePerMonth
                widget: string
              - label: CTA
                name: cta
                widget: string
              - label: Benefits
                name: benefits
                widget: list
                fields:
                  - {label: Text, name: text, widget: string}
          - label: Enterpise
            name: enterpise
            widget: object
            fields:
              - label: CTA
                name: cta
                widget: string
              - label: Benefits
                name: benefits
                widget: list
                fields:
                  - {label: Text, name: text, widget: string}
          - label: FAQs
            name: faqs
            widget: list
            fields:
              - label: Question
                name: question
                widget: string
              - label: Answer
                name: answer
                widget: list
          - label: 'Footer CTA'
            name: footerCta
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: subtitle
                name: subtitle
                widget: string
              - label: 'CTA Text'
                name: ctaText
                widget: string
      - label: "Home"
        name: "home"
        file: content/pages/home/home.json
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: 'CTA Text', name: ctaText, widget: string}
          - {label: 'Trial Text', name: trialText, widget: string}
          - label: 'Feature 1 - Data'
            name: featureData
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Copy
                name: copy
                widget: string
              - label: Tag
                name: tag
                widget: string
              - label: CTA
                name: ctaText
                widget: string
                required: false
              - label: CTA To
                name: ctaTo
                widget: string
                required: false
          - label: 'Feature 2 - Magic Actions'
            name: featureMagicActions
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Copy
                name: copy
                widget: string
              - label: Tag
                name: tag
                widget: string
              - label: CTA
                name: ctaText
                widget: string
                required: false
              - label: CTA To
                name: ctaText
                widget: string
                required: false
          - label: 'Feature 3 - Customer Timeline'
            name: featureTimeline
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Copy
                name: copy
                widget: string
              - label: Tag
                name: tag
                widget: string
              - label: CTA
                name: ctaText
                widget: string
                required: false
              - label: CTA To
                name: ctaText
                widget: string
                required: false
          - label: 'Feature 4 - Data Driven'
            name: featureAnalytics
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Copy
                name: copy
                widget: string
              - label: Tag
                name: tag
                widget: string
              - label: CTA
                name: ctaText
                widget: string
                required: false
              - label: CTA To
                name: ctaText
                widget: string
                required: false
          - label: 'Feature 5 - Privacy Compliance'
            name: featurePrivacy
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Copy
                name: copy
                widget: string
              - label: Tag
                name: tag
                widget: string
              - label: CTA
                name: ctaText
                widget: string
                required: false
              - label: CTA To
                name: ctaText
                widget: string
                required: false
          - label: 'Customers'
            name: customers
            widget: list
            fields:
              - label: Testimonial
                name: testimonial
                widget: string
              - label: Name
                name: name
                widget: string
              - label: Job
                name: job
                widget: string
              - label: Image
                name: image
                widget: image
          - label: 'Footer CTA'
            name: footerCta
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: subtitle
                name: subtitle
                widget: string
              - label: 'CTA Text'
                name: ctaText
                widget: string
